# Generated by Django 4.0.6 on 2022-08-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_myuser_alter_twofactorauth_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='salt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
